name: sync-api
on:
  push:
    branches:
      - master
    paths:
#       TODO disable match all paths when workflow run fluently
      - '**'
#      - 'pkg/yurtappmanager/apis/**'
#      - 'pkg/yurtappmanager/client/**'

jobs:
  sync-core-api:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v3
        env:
          GO_VERSION: '1.17'
          GOLANGCI_VERSION: 'v1.45'
        with:
          go-version: ${{ env.GO_VERSION }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
          echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}

      - name: Sync to api Repo
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SYNC_API_SECRET }}
          VERSION: ${{ steps.get_version.outputs.VERSION }}
          TAG: ${{ steps.get_version.outputs.TAG }}
          COMMIT_ID: ${{ github.sha }}
        run: |
          bash ./hack/lib/sync-api.sh
